language: node_js
node_js: lts/*
before_script:
  - npm install -g gitbook-cli
  - gitbook install
script: gitbook build
before_deploy: 
  - touch _book/.nojekyll
  - echo "guide.mdeditor.org" > _book/CNAME
deploy:
  provider: pages:git
  edge: true # opt in to dpl v2
  local_dir: _book
# safelist
branches:
  only:
  - master
